print(r"""
 __  __    _    _____ _____ __  __    _    _____ ___ _  __    _    
|  \/  |  / \  |_   _| ____|  \/  |  / \  |_   _|_ _| |/ /   / \   
| |\/| | / _ \   | | |  _| | |\/| | / _ \   | |  | || ' /   / _ \  
| |  | |/ ___ \  | | | |___| |  | |/ ___ \  | |  | || . \  / ___ \ 
|_|  |_/_/   \_\ |_| |_____|_|  |_/_/   \_\ |_| |___|_|\_\/_/   \_\
 
+----------------------+
|   RANDOM MATEMATIKA  |
|   naj trpi generator |
+----------------------+
""")
import random
matematika_matura_vse_snovi = [
    # 4.1 Osnove logike
    "osnove logike",
    "izjave in povezave med izjavami",
    "sestavljene izjave",
    "vrstni red logičnih operacij",
    "tavtologija",
    "enakovredne izjave",

    # 4.2 Množice
    "množice",
    "element množice",
    "pripadnost elementa množici",
    "podmnožica",
    "prazna množica",
    "univerzalna množica",
    "simbolni zapisi množic",
    "Vennov diagram",
    "presek množic",
    "unija množic",
    "razlika množic",
    "komplement množice",
    "[VR] lastnosti operacij z množicami",
    "potenčna množica",
    "kartezični produkt množic",
    "moč množice",
    "[VR] moč potenčne množice",

    # 4.3 Številske množice
    "naravna števila",
    "cela števila",
    "računske operacije in njihove lastnosti",
    "praštevila",
    "sestavljena števila",
    "[VR] matematična indukcija",
    "desetiški mestni zapis",
    "kriteriji deljivosti z 2, 3, 4, 5, 6, 8, 9 in 10",
    "relacija deljivosti",
    "največji skupni delitelj",
    "najmanjši skupni večkratnik",
    "osnovni izrek o deljenju",
    "[VR] Evklidov algoritem",
    "desetiški številski sestav",
    "[VR] dvojiški številski sestav",

    "racionalna števila",
    "računanje z racionalnimi števili",
    "desetiški zapis racionalnih števil",
    "deleži",
    "odstotki",
    "procentni račun",

    "realna števila",
    "iracionalna števila",
    "realna števila na številski premici",
    "intervali",
    "končni decimalni približki",
    "absolutna vrednost realnega števila",
    "lastnosti absolutne vrednosti",
    "enačbe z absolutno vrednostjo",
    "[VR] neenačbe z absolutno vrednostjo",
    "absolutna napaka",
    "relativna napaka",

    "kompleksna števila",
    "geometrijska predstavitev kompleksnih števil",
    "računske operacije s kompleksnimi števili",
    "potence števila i",
    "konjugirano kompleksno število",
    "absolutna vrednost kompleksnega števila",
    "deljenje kompleksnih števil",
    "reševanje enačb z realnimi koeficienti v kompleksnih številih",

    # 4.4 Algebrski izrazi, enačbe in neenačbe
    "algebrski izrazi",
    "računske operacije z izrazi",
    "potenciranje izrazov",
    "razstavljanje izrazov",
    "računanje z algebrskimi ulomki",
    "enačbe",
    "neenačbe",
    "linearna enačba",
    "razcepna enačba",
    "[VR] linearna enačba s parametrom",
    "linearna neenačba",
    "[VR] linearna neenačba s parametrom",

    # 4.5 Potence in koreni
    "potence z naravnim eksponentom",
    "potence s celim eksponentom",
    "n-ti koreni",
    "potence z racionalnim eksponentom",
    "kvadratni koreni",
    "kubični koreni",
    "[VR] iracionalne enačbe",

    # 4.6 Geometrija v ravnini in prostoru
    "točke",
    "premice",
    "krožnice v ravnini",
    "razdalja",
    "daljica",
    "nosilka daljice",
    "simetrala",
    "poltrak",
    "kot",
    "vrste kotov",
    "odnosi med koti",
    "trikotnik",
    "večkotnik",
    "znamenite točke trikotnika",
    "togi premiki",
    "skladnost",
    "vzporedni premik",
    "zrcaljenje",
    "vrtež",
    "orientacija trikotnika",
    "pravokotna projekcija",
    "središčni kot",
    "obodni kot",
    "kot v polkrogu",
    "središčni razteg",
    "podobnost",
    "izreki v pravokotnem trikotniku",
    "kosinusni izrek",
    "sinusni izrek",
    "[VR] množice točk v prostoru",
    "vzporednost premic in ravnin v prostoru",
    "pravokotnost premic in ravnin v prostoru",
    "pravokotna projekcija premice na ravnino",

    # 4.7 Geometrijski liki in telesa
    "ploščine geometrijskih likov",
    "Heronova formula",
    "polmer trikotniku včrtanega kroga",
    "polmer trikotniku očrtanega kroga",
    "prizma",
    "valj",
    "piramida",
    "stožec",
    "krogla",
    "površina prizme",
    "prostornina prizme",
    "površina valja",
    "prostornina valja",
    "površina piramide",
    "prostornina piramide",
    "površina stožca",
    "prostornina stožca",
    "površina krogle",
    "prostornina krogle",
    "[VR] Cavalierijevo pravilo",
    "[VR] poševna telesa",
    "[VR] vrtenine",
    "geometrijski matematični problemi",

    # 4.8 Vektorji
    "vektorji v ravnini",
    "vektorji v prostoru",
    "opredelitev vektorjev",
    "seštevanje vektorjev",
    "množenje vektorja s skalarjem",
    "kolinearnost vektorjev",
    "koplanarnost vektorjev",
    "razvoj vektorjev po bazi",
    "pravokotna projekcija vektorja",
    "linearna kombinacija vektorjev",
    "[VR] linearna neodvisnost vektorjev",
    "baza v ravnini",
    "baza v prostoru",
    "krajevni vektor točke",
    "zapis vektorja s koordinatami",
    "računske operacije z vektorji po komponentah",
    "skalarni produkt",
    "kot med vektorjema",
    "dolžina vektorja",
    "[VR] uporaba vektorskega računa v trikotniku",
    "[VR] uporaba vektorskega računa v paralelogramu",
    "[VR] težišče",
    "povezava skalarnega produkta in kosinusnega izreka",

    # 4.9 Koordinatni sistem
    "pravokotni koordinatni sistem v ravnini",
    "množice točk v ravnini",
    "razdalja med točkama v koordinatni ravnini",
    "ploščina trikotnika v koordinatni ravnini",

    # 4.10 Funkcije
    "funkcije",
    "definicija funkcije",
    "definicijsko območje funkcije",
    "zaloga vrednosti funkcije",
    "injektivnost funkcije",
    "surjektivnost funkcije",
    "bijektivnost funkcije",
    "naraščanje funkcije",
    "padanje funkcije",
    "sodost funkcije",
    "lihost funkcije",
    "sestavljene funkcije",
    "inverzna funkcija",
    "transformacije grafov funkcij",
    "limita funkcije",
    "posebni primeri limit",
    "zveznost funkcije",
    "[VR] lastnosti zveznih funkcij na zaprtem intervalu",
    "[VR] iskanje ničel z uporabo tehnologije",

    # 4.10.1 Linearna funkcija
    "linearna funkcija",
    "graf linearne funkcije",
    "enačbe premice v ravnini",
    "kot med premicama",
    "sistem linearnih enačb",
    "[VR] Gaussova eliminacijska metoda",
    "[VR] sistem linearnih neenačb",
    "modeliranje z linearno funkcijo",

    # 4.10.2 Potenčna funkcija
    "potenčna funkcija",
    "potenčna funkcija z naravnim eksponentom",
    "potenčna funkcija z negativnim celim eksponentom",
    "modeliranje s potenčno funkcijo",

    # 4.10.3 Korenska funkcija
    "korenska funkcija",
    "graf korenske funkcije",
    "korenska funkcija kot inverzna funkcija",

    # 4.10.4 Kvadratna funkcija
    "kvadratna funkcija",
    "graf kvadratne funkcije",
    "teme parabole",
    "ničle kvadratne funkcije",
    "načini zapisa kvadratne funkcije",
    "[VR] ekstremalni problemi s kvadratno funkcijo",
    "Viètovi pravili",
    "kvadratna enačba",
    "presečišče parabole in premice",
    "presečišče dveh parabol",
    "kvadratna neenačba",
    "[VR] sistem kvadratnih neenačb",
    "[VR] modeliranje s kvadratno funkcijo",

    # 4.10.5 Eksponentna funkcija
    "eksponentna funkcija",
    "graf eksponentne funkcije",
    "eksponentne enačbe",
    "[VR] grafično reševanje eksponentne neenačbe",
    "eksponentna rast",
    "modeliranje z eksponentno funkcijo",

    # 4.10.6 Logaritemska funkcija
    "logaritemska funkcija",
    "graf logaritemske funkcije",
    "logaritem",
    "pravila za računanje z logaritmi",
    "desetiški logaritem",
    "naravni logaritem",
    "[VR] prehod k novi osnovi logaritma",
    "logaritemske enačbe",
    "[VR] branje logaritemske skale",
    "[VR] modeliranje z logaritemsko funkcijo",

    # 4.10.7 Polinomska funkcija
    "polinomska funkcija",
    "graf polinomske funkcije",
    "računske operacije s polinomi",
    "osnovni izrek o deljenju polinomov",
    "ničle polinomske funkcije",
    "osnovni izrek algebre",
    "Hornerjev algoritem",
    "analiza grafa polinomske funkcije",
    "polinomske enačbe",
    "polinomske neenačbe",
    "[VR] metoda bisekcije",
    "[VR] modeliranje s polinomi",

    # 4.10.8 Racionalna funkcija
    "racionalna funkcija",
    "graf racionalne funkcije",
    "ničle racionalne funkcije",
    "poli racionalne funkcije",
    "asimptote racionalne funkcije",
    "racionalne enačbe",
    "[VR] racionalne neenačbe",

    # 4.10.9 Kotne funkcije / trigonometrija
    "kotne funkcije v pravokotnem trikotniku",
    "kotne funkcije na enotski krožnici",
    "grafi kotnih funkcij",
    "lastnosti kotnih funkcij",
    "transformacije grafov kotnih funkcij",
    "adicijski izreki",
    "kotne funkcije dvojnih kotov",
    "[VR] kotne funkcije polovičnih kotov",
    "računanje vrednosti krožnih funkcij",
    "[VR] grafi in lastnosti krožnih funkcij",
    "trigonometrijske enačbe",
    "[VR] faktorizacija trigonometričnih izrazov",
    "[VR] kotne funkcije v tehniki in naravoslovju",
    "problemske naloge iz trigonometrije",

    # 4.11 Stožnice
    "stožnice",
    "algebrski zapis krivulj drugega reda",
    "krožnica v središčni legi",
    "krožnica v premaknjeni legi",
    "elipsa v središčni legi",
    "elipsa v premaknjeni legi",
    "hiperbola v središčni legi",
    "parabola v temenski legi",
    "[VR] hiperbola v premaknjeni legi",
    "[VR] parabola v premaknjeni legi",
    "[VR] tangente stožnic",
    "presečišča stožnice s premico",
    "presečišča stožnic",

    # 4.12 Zaporedja in vrste
    "zaporedja",
    "definicija zaporedja",
    "končno zaporedje",
    "neskončno zaporedje",
    "monotonost zaporedja",
    "omejenost zaporedja",
    "konvergentnost zaporedja",
    "aritmetično zaporedje",
    "geometrijsko zaporedje",
    "vsota prvih n členov aritmetičnega zaporedja",
    "vsota členov geometrijskega zaporedja",
    "limita zaporedja",
    "vrste",
    "konvergenca geometrijske vrste",
    "obrestni račun",
    "anuitete",
    "amortizacijski načrt",

    # 4.13 Diferencialni račun
    "diferencialni račun",
    "diferenčni količnik",
    "odvod",
    "geometrijski pomen odvoda",
    "pravila za odvajanje",
    "odvodi osnovnih funkcij",
    "uporaba odvoda",
    "ekstremi funkcije",
    "naraščanje funkcije z odvodom",
    "padanje funkcije z odvodom",
    "[VR] drugi odvod funkcije",
    "[VR] prevoj funkcije",
    "[VR] konveksnost funkcije",
    "[VR] konkavnost funkcije",
    "[VR] zveznost odvedljivih funkcij",
    "ekstremalni problemi",
    "[VR] modeliranje z diferencialnim računom",

    # 4.14 Integralski račun
    "integralski račun",
    "nedoločeni integral",
    "primitivna funkcija",
    "lastnosti nedoločenega integrala",
    "[VR] uvedba nove spremenljivke pri integriranju",
    "[VR] integracija per partes",
    "[VR] integracija racionalnih funkcij",
    "določeni integral",
    "lastnosti določenega integrala",
    "zveza med določenim in nedoločenim integralom",
    "uporaba določenega integrala za ploščine",
    "[VR] uporaba določenega integrala za prostornine vrtenin",

    # 4.15 Kombinatorika
    "kombinatorika",
    "osnovni izrek kombinatorike",
    "kombinatorično drevo",
    "pravilo vsote",
    "permutacije",
    "permutacije s ponavljanjem",
    "variacije",
    "variacije s ponavljanjem",
    "kombinacije",
    "binomski izrek",
    "Pascalov trikotnik",
    "fakulteta n!",

    # 4.16 Verjetnostni račun
    "verjetnostni račun",
    "poskus",
    "dogodek",
    "vzorčni prostor",
    "računanje z dogodki",
    "subjektivna verjetnost",
    "empirična verjetnost",
    "matematična verjetnost",
    "verjetnost dogodka",
    "verjetnost nasprotnega dogodka",
    "verjetnost vsote dogodkov",
    "[VR] pogojna verjetnost",
    "[VR] verjetnost produkta dogodkov",
    "[VR] neodvisna dogodka",
    "[VR] zaporedje neodvisnih poskusov",
    "normalna porazdelitev",

    # 4.17 Statistika
    "statistika",
    "osnovni statistični pojmi",
    "vrste podatkov",
    "zbiranje podatkov",
    "urejanje podatkov",
    "strukturiranje podatkov",
    "stolpčni diagram",
    "pozicijski diagram",
    "tortni diagram",
    "histogram",
    "razsevni diagram",
    "linijski diagram",
    "krivuljni diagram",
    "škatla z brki",
    "aritmetična sredina",
    "mediana",
    "modus",
    "variacijski razmik",
    "standardni odklon",
    "medčetrtinski razmik",
    "statistična naloga"
]

matematika_matura_vse_snovi = random.choice(matematika_matura_vse_snovi)
print(f"Današnje učenje matematike: {matematika_matura_vse_snovi}.")